project:
  output-dir: output

title: "LangChain + LangGraph ğŸ¦¾"
subtitle: "SprÃ¥kmodeller satt i system"

toc: true
language: assets/_quarto_language.yml

format:
  revealjs:
    highlight-style: pygments
    preview-links: auto
    logo: assets/nav-logo-red.svg
    theme: [default, assets/nav.scss]
    slide-number: true